name: Deployment

on:
  workflow_run:
    workflows: ["Testiranje"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Nastavi Docker
        run: |
          docker --version
          docker build -t ${{ secrets.DOCKER_USERNAME }}/news-app:latest .

      - name: Poveži z DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pošlji Docker sliko na DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/news-app:latest
